CONFIG:=$(addprefix ../,$(CONFIG))
include $(CONFIG)

# COMPILER FLAGS
FLAGS_CC := -std=c99
FLAGS_CXX:= -std=c++17

WARNING     :=-Wall -Wextra -pedantic -Wno-write-strings
OPTIMIZATION:=-O3 -Os -fdata-sections -ffunction-sections -fno-exceptions
