#undef LAYER_INPUTS_COUNT
#undef LAYER_OUTPUTS_COUNT
#undef LAYER_ACTIVATION_FUNCTION
#undef LAYER_ACTIVATION_FUNCTION_DERIVATIVE
#undef LAYER_IS_FIRST
#undef LAYER_IS_HIDDEN
#undef LAYER_IS_OUTPUT
#undef LAYER_NEURON_WEIGHTS_COUNT
#undef NEXT_LAYER_NEURON_WEIGHTS_COUNT

// LAYER 0
#if LAYER_IDX == 0
#define LAYER_INPUTS_COUNT                   L0_INPUTS_COUNT
#define LAYER_OUTPUTS_COUNT                  L0_OUTPUTS_COUNT
#define LAYER_ACTIVATION_FUNCTION            L0_ACTIVATION_FUNCTION
#define LAYER_ACTIVATION_FUNCTION_DERIVATIVE L0_ACTIVATION_FUNCTION_DERIVATIVE

#ifdef L0_NEURON_WEIGHTS_COUNT
#define LAYER_NEURON_WEIGHTS_COUNT L0_NEURON_WEIGHTS_COUNT
#else
#define LAYER_NEURON_WEIGHTS_COUNT (LAYER_INPUTS_COUNT + 1)
#endif

#ifdef L0_NEURONS_COUNT
#define LAYER_NEURONS_COUNT L0_NEURONS_COUNT
#else
#define LAYER_NEURONS_COUNT L0_OUTPUTS_COUNT
#endif

#ifdef L1_NEURONS_COUNT
#define NEXT_LAYER_NEURONS_COUNT L1_NEURONS_COUNT
#else
#define NEXT_LAYER_NEURONS_COUNT L1_OUTPUTS_COUNT
#endif
// LAYER 0

#elif LAYER_IDX == 1
#define LAYER_INPUTS_COUNT                   L1_INPUTS_COUNT
#define LAYER_OUTPUTS_COUNT                  L1_OUTPUTS_COUNT
#define LAYER_ACTIVATION_FUNCTION            L1_ACTIVATION_FUNCTION
#define LAYER_ACTIVATION_FUNCTION_DERIVATIVE L1_ACTIVATION_FUNCTION_DERIVATIVE
// AND SO ON ...
// I'LL GENERATE MORE WHEN I'M DONE WITH ALL DEFS
#endif

#if LAYER_IDX == LAYER_COUNT - 1
#define LAYER_IS_OUTPUT
#endif

#if LAYER_IDX == 0
#define LAYER_IS_FIRST
#endif

#ifndef LAYER_IS_OUTPUT
#define LAYER_IS_HIDDEN
#endif
