# PROJECT DIRS
DIR_INC_MAIN:=inc
DIRS_INC=$(DIR_INC_MAIN) inc/vendor $(DIR_FOSL)
DIR_SRC:=src
DIR_OBJ:=obj
DIR_DEP:=dep
DIR_BIN:=bin

# PROJECT FILES
ELF:=$(DIR_BIN)/firmware.elf
HEX:=$(DIR_BIN)/firmware.hex
BIN:=$(DIR_BIN)/firmware.bin
ASM:=$(DIR_BIN)/firmware.asm

# LIB DIRS
DIR_LIB_INC=$(DIR_LIB)/inc
DIR_LIB_LIB=$(DIR_LIB)/lib

# OTHER DIRS
DIR_FOSL=$(dir $(realpath $(CONFIG)))

# TOOLCHAIN
TOOLCHAIN:=
CC     =$(TOOLCHAIN)gcc
CXX    =$(TOOLCHAIN)g++
ASMC   =$(TOOLCHAIN)gcc
NVCC   =$(TOOLCHAIN)nvcc
LD     =$(TOOLCHAIN)g++
AR     =$(TOOLCHAIN)ar
OBJCOPY=$(TOOLCHAIN)objcopy
OBJDUMP=$(TOOLCHAIN)objdump
SIZE   =$(TOOLCHAIN)size
STRIP  =$(TOOLCHAIN)strip
