CONFIG:=$(addprefix ../,$(CONFIG))
include $(CONFIG)

NAME_EXAMPLE:=$(shell echo $(realpath .) | sed -E 's/.*\/([^\/]*\/[^\/]*)$$/\1/')

# TARGET
MCU     :=atmega328p
F_CPU   :=16000000
TIO_BAUD:=9600
PROG    :=arduino
PORT    :=/dev/ttyUSB0
